#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CallCenter")]
	public partial class dbCallCenterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMenu(Menu instance);
    partial void UpdateMenu(Menu instance);
    partial void DeleteMenu(Menu instance);
    partial void InsertTo(To instance);
    partial void UpdateTo(To instance);
    partial void DeleteTo(To instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNhom(Nhom instance);
    partial void UpdateNhom(Nhom instance);
    partial void DeleteNhom(Nhom instance);
    partial void InsertPhanQuyenNguoiDung(PhanQuyenNguoiDung instance);
    partial void UpdatePhanQuyenNguoiDung(PhanQuyenNguoiDung instance);
    partial void DeletePhanQuyenNguoiDung(PhanQuyenNguoiDung instance);
    partial void InsertPhanQuyenNhom(PhanQuyenNhom instance);
    partial void UpdatePhanQuyenNhom(PhanQuyenNhom instance);
    partial void DeletePhanQuyenNhom(PhanQuyenNhom instance);
    partial void InsertLoaiTiepNhan(LoaiTiepNhan instance);
    partial void UpdateLoaiTiepNhan(LoaiTiepNhan instance);
    partial void DeleteLoaiTiepNhan(LoaiTiepNhan instance);
    partial void InsertTiepNhan(TiepNhan instance);
    partial void UpdateTiepNhan(TiepNhan instance);
    partial void DeleteTiepNhan(TiepNhan instance);
    #endregion
		
		public dbCallCenterDataContext() : 
				base(global::CallCenter.Properties.Settings.Default.CallCenterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbCallCenterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbCallCenterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbCallCenterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbCallCenterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<To> Tos
		{
			get
			{
				return this.GetTable<To>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<Nhom> Nhoms
		{
			get
			{
				return this.GetTable<Nhom>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyenNguoiDung> PhanQuyenNguoiDungs
		{
			get
			{
				return this.GetTable<PhanQuyenNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyenNhom> PhanQuyenNhoms
		{
			get
			{
				return this.GetTable<PhanQuyenNhom>();
			}
		}
		
		public System.Data.Linq.Table<HOSOGOC> HOSOGOCs
		{
			get
			{
				return this.GetTable<HOSOGOC>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTiepNhan> LoaiTiepNhans
		{
			get
			{
				return this.GetTable<LoaiTiepNhan>();
			}
		}
		
		public System.Data.Linq.Table<TiepNhan> TiepNhans
		{
			get
			{
				return this.GetTable<TiepNhan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMenu;
		
		private System.Nullable<int> _STT;
		
		private string _TenMenu;
		
		private string _TextMenu;
		
		private string _TenMenuCha;
		
		private string _TextMenuCha;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private EntitySet<PhanQuyenNguoiDung> _PhanQuyenNguoiDungs;
		
		private EntitySet<PhanQuyenNhom> _PhanQuyenNhoms;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMenuChanging(int value);
    partial void OnMaMenuChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnTenMenuChanging(string value);
    partial void OnTenMenuChanged();
    partial void OnTextMenuChanging(string value);
    partial void OnTextMenuChanged();
    partial void OnTenMenuChaChanging(string value);
    partial void OnTenMenuChaChanged();
    partial void OnTextMenuChaChanging(string value);
    partial void OnTextMenuChaChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public Menu()
		{
			this._PhanQuyenNguoiDungs = new EntitySet<PhanQuyenNguoiDung>(new Action<PhanQuyenNguoiDung>(this.attach_PhanQuyenNguoiDungs), new Action<PhanQuyenNguoiDung>(this.detach_PhanQuyenNguoiDungs));
			this._PhanQuyenNhoms = new EntitySet<PhanQuyenNhom>(new Action<PhanQuyenNhom>(this.attach_PhanQuyenNhoms), new Action<PhanQuyenNhom>(this.detach_PhanQuyenNhoms));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMenu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMenu
		{
			get
			{
				return this._MaMenu;
			}
			set
			{
				if ((this._MaMenu != value))
				{
					this.OnMaMenuChanging(value);
					this.SendPropertyChanging();
					this._MaMenu = value;
					this.SendPropertyChanged("MaMenu");
					this.OnMaMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMenu", DbType="VarChar(50)")]
		public string TenMenu
		{
			get
			{
				return this._TenMenu;
			}
			set
			{
				if ((this._TenMenu != value))
				{
					this.OnTenMenuChanging(value);
					this.SendPropertyChanging();
					this._TenMenu = value;
					this.SendPropertyChanged("TenMenu");
					this.OnTenMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextMenu", DbType="NVarChar(50)")]
		public string TextMenu
		{
			get
			{
				return this._TextMenu;
			}
			set
			{
				if ((this._TextMenu != value))
				{
					this.OnTextMenuChanging(value);
					this.SendPropertyChanging();
					this._TextMenu = value;
					this.SendPropertyChanged("TextMenu");
					this.OnTextMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMenuCha", DbType="VarChar(50)")]
		public string TenMenuCha
		{
			get
			{
				return this._TenMenuCha;
			}
			set
			{
				if ((this._TenMenuCha != value))
				{
					this.OnTenMenuChaChanging(value);
					this.SendPropertyChanging();
					this._TenMenuCha = value;
					this.SendPropertyChanged("TenMenuCha");
					this.OnTenMenuChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextMenuCha", DbType="NVarChar(50)")]
		public string TextMenuCha
		{
			get
			{
				return this._TextMenuCha;
			}
			set
			{
				if ((this._TextMenuCha != value))
				{
					this.OnTextMenuChaChanging(value);
					this.SendPropertyChanging();
					this._TextMenuCha = value;
					this.SendPropertyChanged("TextMenuCha");
					this.OnTextMenuChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_PhanQuyenNguoiDung", Storage="_PhanQuyenNguoiDungs", ThisKey="MaMenu", OtherKey="MaMenu")]
		public EntitySet<PhanQuyenNguoiDung> PhanQuyenNguoiDungs
		{
			get
			{
				return this._PhanQuyenNguoiDungs;
			}
			set
			{
				this._PhanQuyenNguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_PhanQuyenNhom", Storage="_PhanQuyenNhoms", ThisKey="MaMenu", OtherKey="MaMenu")]
		public EntitySet<PhanQuyenNhom> PhanQuyenNhoms
		{
			get
			{
				return this._PhanQuyenNhoms;
			}
			set
			{
				this._PhanQuyenNhoms.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Menu = this;
		}
		
		private void detach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Menu = null;
		}
		
		private void attach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.Menu = this;
		}
		
		private void detach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[To]")]
	public partial class To : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTo;
		
		private string _TenTo;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaToChanging(int value);
    partial void OnMaToChanged();
    partial void OnTenToChanging(string value);
    partial void OnTenToChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public To()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTo
		{
			get
			{
				return this._MaTo;
			}
			set
			{
				if ((this._MaTo != value))
				{
					this.OnMaToChanging(value);
					this.SendPropertyChanging();
					this._MaTo = value;
					this.SendPropertyChanged("MaTo");
					this.OnMaToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTo", DbType="NVarChar(50)")]
		public string TenTo
		{
			get
			{
				return this._TenTo;
			}
			set
			{
				if ((this._TenTo != value))
				{
					this.OnTenToChanging(value);
					this.SendPropertyChanging();
					this._TenTo = value;
					this.SendPropertyChanged("TenTo");
					this.OnTenToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="To_NguoiDung", Storage="_NguoiDungs", ThisKey="MaTo", OtherKey="MaTo")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.To = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.To = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaND;
		
		private System.Nullable<int> _STT;
		
		private string _HoTen;
		
		private string _DienThoai;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<System.DateTime> _LoginDate;
		
		private System.Nullable<int> _NamVaoLam;
		
		private System.Nullable<int> _NgayPhepNamCu;
		
		private System.Nullable<int> _NgayPhepNamMoi;
		
		private System.Nullable<int> _TongNgayPhep;
		
		private bool _Admin;
		
		private bool _PhoGiamDoc;
		
		private bool _Doi;
		
		private bool _ToTruong;
		
		private bool _HanhThu;
		
		private bool _DongNuoc;
		
		private bool _VanPhong;
		
		private bool _ChamCong;
		
		private bool _An;
		
		private System.Nullable<int> _MaTo;
		
		private System.Nullable<int> _MaNhom;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private EntitySet<PhanQuyenNguoiDung> _PhanQuyenNguoiDungs;
		
		private EntityRef<To> _To;
		
		private EntityRef<Nhom> _Nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNDChanging(int value);
    partial void OnMaNDChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLoginDateChanged();
    partial void OnNamVaoLamChanging(System.Nullable<int> value);
    partial void OnNamVaoLamChanged();
    partial void OnNgayPhepNamCuChanging(System.Nullable<int> value);
    partial void OnNgayPhepNamCuChanged();
    partial void OnNgayPhepNamMoiChanging(System.Nullable<int> value);
    partial void OnNgayPhepNamMoiChanged();
    partial void OnTongNgayPhepChanging(System.Nullable<int> value);
    partial void OnTongNgayPhepChanged();
    partial void OnAdminChanging(bool value);
    partial void OnAdminChanged();
    partial void OnPhoGiamDocChanging(bool value);
    partial void OnPhoGiamDocChanged();
    partial void OnDoiChanging(bool value);
    partial void OnDoiChanged();
    partial void OnToTruongChanging(bool value);
    partial void OnToTruongChanged();
    partial void OnHanhThuChanging(bool value);
    partial void OnHanhThuChanged();
    partial void OnDongNuocChanging(bool value);
    partial void OnDongNuocChanged();
    partial void OnVanPhongChanging(bool value);
    partial void OnVanPhongChanged();
    partial void OnChamCongChanging(bool value);
    partial void OnChamCongChanged();
    partial void OnAnChanging(bool value);
    partial void OnAnChanged();
    partial void OnMaToChanging(System.Nullable<int> value);
    partial void OnMaToChanged();
    partial void OnMaNhomChanging(System.Nullable<int> value);
    partial void OnMaNhomChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public NguoiDung()
		{
			this._PhanQuyenNguoiDungs = new EntitySet<PhanQuyenNguoiDung>(new Action<PhanQuyenNguoiDung>(this.attach_PhanQuyenNguoiDungs), new Action<PhanQuyenNguoiDung>(this.detach_PhanQuyenNguoiDungs));
			this._To = default(EntityRef<To>);
			this._Nhom = default(EntityRef<Nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaND", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaND
		{
			get
			{
				return this._MaND;
			}
			set
			{
				if ((this._MaND != value))
				{
					this.OnMaNDChanging(value);
					this.SendPropertyChanging();
					this._MaND = value;
					this.SendPropertyChanged("MaND");
					this.OnMaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(200)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LoginDate
		{
			get
			{
				return this._LoginDate;
			}
			set
			{
				if ((this._LoginDate != value))
				{
					this.OnLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LoginDate = value;
					this.SendPropertyChanged("LoginDate");
					this.OnLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamVaoLam", DbType="Int")]
		public System.Nullable<int> NamVaoLam
		{
			get
			{
				return this._NamVaoLam;
			}
			set
			{
				if ((this._NamVaoLam != value))
				{
					this.OnNamVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NamVaoLam = value;
					this.SendPropertyChanged("NamVaoLam");
					this.OnNamVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhepNamCu", DbType="Int")]
		public System.Nullable<int> NgayPhepNamCu
		{
			get
			{
				return this._NgayPhepNamCu;
			}
			set
			{
				if ((this._NgayPhepNamCu != value))
				{
					this.OnNgayPhepNamCuChanging(value);
					this.SendPropertyChanging();
					this._NgayPhepNamCu = value;
					this.SendPropertyChanged("NgayPhepNamCu");
					this.OnNgayPhepNamCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhepNamMoi", DbType="Int")]
		public System.Nullable<int> NgayPhepNamMoi
		{
			get
			{
				return this._NgayPhepNamMoi;
			}
			set
			{
				if ((this._NgayPhepNamMoi != value))
				{
					this.OnNgayPhepNamMoiChanging(value);
					this.SendPropertyChanging();
					this._NgayPhepNamMoi = value;
					this.SendPropertyChanged("NgayPhepNamMoi");
					this.OnNgayPhepNamMoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongNgayPhep", DbType="Int")]
		public System.Nullable<int> TongNgayPhep
		{
			get
			{
				return this._TongNgayPhep;
			}
			set
			{
				if ((this._TongNgayPhep != value))
				{
					this.OnTongNgayPhepChanging(value);
					this.SendPropertyChanging();
					this._TongNgayPhep = value;
					this.SendPropertyChanged("TongNgayPhep");
					this.OnTongNgayPhepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin", DbType="Bit NOT NULL")]
		public bool Admin
		{
			get
			{
				return this._Admin;
			}
			set
			{
				if ((this._Admin != value))
				{
					this.OnAdminChanging(value);
					this.SendPropertyChanging();
					this._Admin = value;
					this.SendPropertyChanged("Admin");
					this.OnAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoGiamDoc", DbType="Bit NOT NULL")]
		public bool PhoGiamDoc
		{
			get
			{
				return this._PhoGiamDoc;
			}
			set
			{
				if ((this._PhoGiamDoc != value))
				{
					this.OnPhoGiamDocChanging(value);
					this.SendPropertyChanging();
					this._PhoGiamDoc = value;
					this.SendPropertyChanged("PhoGiamDoc");
					this.OnPhoGiamDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doi", DbType="Bit NOT NULL")]
		public bool Doi
		{
			get
			{
				return this._Doi;
			}
			set
			{
				if ((this._Doi != value))
				{
					this.OnDoiChanging(value);
					this.SendPropertyChanging();
					this._Doi = value;
					this.SendPropertyChanged("Doi");
					this.OnDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToTruong", DbType="Bit NOT NULL")]
		public bool ToTruong
		{
			get
			{
				return this._ToTruong;
			}
			set
			{
				if ((this._ToTruong != value))
				{
					this.OnToTruongChanging(value);
					this.SendPropertyChanging();
					this._ToTruong = value;
					this.SendPropertyChanged("ToTruong");
					this.OnToTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanhThu", DbType="Bit NOT NULL")]
		public bool HanhThu
		{
			get
			{
				return this._HanhThu;
			}
			set
			{
				if ((this._HanhThu != value))
				{
					this.OnHanhThuChanging(value);
					this.SendPropertyChanging();
					this._HanhThu = value;
					this.SendPropertyChanged("HanhThu");
					this.OnHanhThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongNuoc", DbType="Bit NOT NULL")]
		public bool DongNuoc
		{
			get
			{
				return this._DongNuoc;
			}
			set
			{
				if ((this._DongNuoc != value))
				{
					this.OnDongNuocChanging(value);
					this.SendPropertyChanging();
					this._DongNuoc = value;
					this.SendPropertyChanged("DongNuoc");
					this.OnDongNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanPhong", DbType="Bit NOT NULL")]
		public bool VanPhong
		{
			get
			{
				return this._VanPhong;
			}
			set
			{
				if ((this._VanPhong != value))
				{
					this.OnVanPhongChanging(value);
					this.SendPropertyChanging();
					this._VanPhong = value;
					this.SendPropertyChanged("VanPhong");
					this.OnVanPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChamCong", DbType="Bit NOT NULL")]
		public bool ChamCong
		{
			get
			{
				return this._ChamCong;
			}
			set
			{
				if ((this._ChamCong != value))
				{
					this.OnChamCongChanging(value);
					this.SendPropertyChanging();
					this._ChamCong = value;
					this.SendPropertyChanged("ChamCong");
					this.OnChamCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_An", DbType="Bit NOT NULL")]
		public bool An
		{
			get
			{
				return this._An;
			}
			set
			{
				if ((this._An != value))
				{
					this.OnAnChanging(value);
					this.SendPropertyChanging();
					this._An = value;
					this.SendPropertyChanged("An");
					this.OnAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTo", DbType="Int")]
		public System.Nullable<int> MaTo
		{
			get
			{
				return this._MaTo;
			}
			set
			{
				if ((this._MaTo != value))
				{
					if (this._To.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaToChanging(value);
					this.SendPropertyChanging();
					this._MaTo = value;
					this.SendPropertyChanged("MaTo");
					this.OnMaToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int")]
		public System.Nullable<int> MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._Nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_PhanQuyenNguoiDung", Storage="_PhanQuyenNguoiDungs", ThisKey="MaND", OtherKey="MaND")]
		public EntitySet<PhanQuyenNguoiDung> PhanQuyenNguoiDungs
		{
			get
			{
				return this._PhanQuyenNguoiDungs;
			}
			set
			{
				this._PhanQuyenNguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="To_NguoiDung", Storage="_To", ThisKey="MaTo", OtherKey="MaTo", IsForeignKey=true)]
		public To To
		{
			get
			{
				return this._To.Entity;
			}
			set
			{
				To previousValue = this._To.Entity;
				if (((previousValue != value) 
							|| (this._To.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._To.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._To.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaTo = value.MaTo;
					}
					else
					{
						this._MaTo = default(Nullable<int>);
					}
					this.SendPropertyChanged("To");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_NguoiDung", Storage="_Nhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhom")]
	public partial class Nhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhom;
		
		private string _TenNhom;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
		private EntitySet<PhanQuyenNhom> _PhanQuyenNhoms;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public Nhom()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			this._PhanQuyenNhoms = new EntitySet<PhanQuyenNhom>(new Action<PhanQuyenNhom>(this.attach_PhanQuyenNhoms), new Action<PhanQuyenNhom>(this.detach_PhanQuyenNhoms));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_NguoiDung", Storage="_NguoiDungs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_PhanQuyenNhom", Storage="_PhanQuyenNhoms", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<PhanQuyenNhom> PhanQuyenNhoms
		{
			get
			{
				return this._PhanQuyenNhoms;
			}
			set
			{
				this._PhanQuyenNhoms.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = null;
		}
		
		private void attach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = this;
		}
		
		private void detach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.Nhom = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyenNguoiDung")]
	public partial class PhanQuyenNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMenu;
		
		private int _MaND;
		
		private bool _ToanQuyen;
		
		private bool _Xem;
		
		private bool _Them;
		
		private bool _Xoa;
		
		private bool _Sua;
		
		private bool _QuanLy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private EntityRef<Menu> _Menu;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMenuChanging(int value);
    partial void OnMaMenuChanged();
    partial void OnMaNDChanging(int value);
    partial void OnMaNDChanged();
    partial void OnToanQuyenChanging(bool value);
    partial void OnToanQuyenChanged();
    partial void OnXemChanging(bool value);
    partial void OnXemChanged();
    partial void OnThemChanging(bool value);
    partial void OnThemChanged();
    partial void OnXoaChanging(bool value);
    partial void OnXoaChanged();
    partial void OnSuaChanging(bool value);
    partial void OnSuaChanged();
    partial void OnQuanLyChanging(bool value);
    partial void OnQuanLyChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public PhanQuyenNguoiDung()
		{
			this._Menu = default(EntityRef<Menu>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMenu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMenu
		{
			get
			{
				return this._MaMenu;
			}
			set
			{
				if ((this._MaMenu != value))
				{
					if (this._Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMenuChanging(value);
					this.SendPropertyChanging();
					this._MaMenu = value;
					this.SendPropertyChanged("MaMenu");
					this.OnMaMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaND", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaND
		{
			get
			{
				return this._MaND;
			}
			set
			{
				if ((this._MaND != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNDChanging(value);
					this.SendPropertyChanging();
					this._MaND = value;
					this.SendPropertyChanged("MaND");
					this.OnMaNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToanQuyen", DbType="Bit NOT NULL")]
		public bool ToanQuyen
		{
			get
			{
				return this._ToanQuyen;
			}
			set
			{
				if ((this._ToanQuyen != value))
				{
					this.OnToanQuyenChanging(value);
					this.SendPropertyChanging();
					this._ToanQuyen = value;
					this.SendPropertyChanged("ToanQuyen");
					this.OnToanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xem", DbType="Bit NOT NULL")]
		public bool Xem
		{
			get
			{
				return this._Xem;
			}
			set
			{
				if ((this._Xem != value))
				{
					this.OnXemChanging(value);
					this.SendPropertyChanging();
					this._Xem = value;
					this.SendPropertyChanged("Xem");
					this.OnXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Them", DbType="Bit NOT NULL")]
		public bool Them
		{
			get
			{
				return this._Them;
			}
			set
			{
				if ((this._Them != value))
				{
					this.OnThemChanging(value);
					this.SendPropertyChanging();
					this._Them = value;
					this.SendPropertyChanged("Them");
					this.OnThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xoa", DbType="Bit NOT NULL")]
		public bool Xoa
		{
			get
			{
				return this._Xoa;
			}
			set
			{
				if ((this._Xoa != value))
				{
					this.OnXoaChanging(value);
					this.SendPropertyChanging();
					this._Xoa = value;
					this.SendPropertyChanged("Xoa");
					this.OnXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sua", DbType="Bit NOT NULL")]
		public bool Sua
		{
			get
			{
				return this._Sua;
			}
			set
			{
				if ((this._Sua != value))
				{
					this.OnSuaChanging(value);
					this.SendPropertyChanging();
					this._Sua = value;
					this.SendPropertyChanged("Sua");
					this.OnSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanLy", DbType="Bit NOT NULL")]
		public bool QuanLy
		{
			get
			{
				return this._QuanLy;
			}
			set
			{
				if ((this._QuanLy != value))
				{
					this.OnQuanLyChanging(value);
					this.SendPropertyChanging();
					this._QuanLy = value;
					this.SendPropertyChanged("QuanLy");
					this.OnQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_PhanQuyenNguoiDung", Storage="_Menu", ThisKey="MaMenu", OtherKey="MaMenu", IsForeignKey=true)]
		public Menu Menu
		{
			get
			{
				return this._Menu.Entity;
			}
			set
			{
				Menu previousValue = this._Menu.Entity;
				if (((previousValue != value) 
							|| (this._Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu.Entity = null;
						previousValue.PhanQuyenNguoiDungs.Remove(this);
					}
					this._Menu.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNguoiDungs.Add(this);
						this._MaMenu = value.MaMenu;
					}
					else
					{
						this._MaMenu = default(int);
					}
					this.SendPropertyChanged("Menu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_PhanQuyenNguoiDung", Storage="_NguoiDung", ThisKey="MaND", OtherKey="MaND", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.PhanQuyenNguoiDungs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNguoiDungs.Add(this);
						this._MaND = value.MaND;
					}
					else
					{
						this._MaND = default(int);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyenNhom")]
	public partial class PhanQuyenNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMenu;
		
		private int _MaNhom;
		
		private bool _ToanQuyen;
		
		private bool _Xem;
		
		private bool _Them;
		
		private bool _Sua;
		
		private bool _Xoa;
		
		private bool _QuanLy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private EntityRef<Menu> _Menu;
		
		private EntityRef<Nhom> _Nhom;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMenuChanging(int value);
    partial void OnMaMenuChanged();
    partial void OnMaNhomChanging(int value);
    partial void OnMaNhomChanged();
    partial void OnToanQuyenChanging(bool value);
    partial void OnToanQuyenChanged();
    partial void OnXemChanging(bool value);
    partial void OnXemChanged();
    partial void OnThemChanging(bool value);
    partial void OnThemChanged();
    partial void OnSuaChanging(bool value);
    partial void OnSuaChanged();
    partial void OnXoaChanging(bool value);
    partial void OnXoaChanged();
    partial void OnQuanLyChanging(bool value);
    partial void OnQuanLyChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public PhanQuyenNhom()
		{
			this._Menu = default(EntityRef<Menu>);
			this._Nhom = default(EntityRef<Nhom>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMenu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMenu
		{
			get
			{
				return this._MaMenu;
			}
			set
			{
				if ((this._MaMenu != value))
				{
					if (this._Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMenuChanging(value);
					this.SendPropertyChanging();
					this._MaMenu = value;
					this.SendPropertyChanged("MaMenu");
					this.OnMaMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._Nhom.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToanQuyen", DbType="Bit NOT NULL")]
		public bool ToanQuyen
		{
			get
			{
				return this._ToanQuyen;
			}
			set
			{
				if ((this._ToanQuyen != value))
				{
					this.OnToanQuyenChanging(value);
					this.SendPropertyChanging();
					this._ToanQuyen = value;
					this.SendPropertyChanged("ToanQuyen");
					this.OnToanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xem", DbType="Bit NOT NULL")]
		public bool Xem
		{
			get
			{
				return this._Xem;
			}
			set
			{
				if ((this._Xem != value))
				{
					this.OnXemChanging(value);
					this.SendPropertyChanging();
					this._Xem = value;
					this.SendPropertyChanged("Xem");
					this.OnXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Them", DbType="Bit NOT NULL")]
		public bool Them
		{
			get
			{
				return this._Them;
			}
			set
			{
				if ((this._Them != value))
				{
					this.OnThemChanging(value);
					this.SendPropertyChanging();
					this._Them = value;
					this.SendPropertyChanged("Them");
					this.OnThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sua", DbType="Bit NOT NULL")]
		public bool Sua
		{
			get
			{
				return this._Sua;
			}
			set
			{
				if ((this._Sua != value))
				{
					this.OnSuaChanging(value);
					this.SendPropertyChanging();
					this._Sua = value;
					this.SendPropertyChanged("Sua");
					this.OnSuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xoa", DbType="Bit NOT NULL")]
		public bool Xoa
		{
			get
			{
				return this._Xoa;
			}
			set
			{
				if ((this._Xoa != value))
				{
					this.OnXoaChanging(value);
					this.SendPropertyChanging();
					this._Xoa = value;
					this.SendPropertyChanged("Xoa");
					this.OnXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuanLy", DbType="Bit NOT NULL")]
		public bool QuanLy
		{
			get
			{
				return this._QuanLy;
			}
			set
			{
				if ((this._QuanLy != value))
				{
					this.OnQuanLyChanging(value);
					this.SendPropertyChanging();
					this._QuanLy = value;
					this.SendPropertyChanged("QuanLy");
					this.OnQuanLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menu_PhanQuyenNhom", Storage="_Menu", ThisKey="MaMenu", OtherKey="MaMenu", IsForeignKey=true)]
		public Menu Menu
		{
			get
			{
				return this._Menu.Entity;
			}
			set
			{
				Menu previousValue = this._Menu.Entity;
				if (((previousValue != value) 
							|| (this._Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menu.Entity = null;
						previousValue.PhanQuyenNhoms.Remove(this);
					}
					this._Menu.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNhoms.Add(this);
						this._MaMenu = value.MaMenu;
					}
					else
					{
						this._MaMenu = default(int);
					}
					this.SendPropertyChanged("Menu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_PhanQuyenNhom", Storage="_Nhom", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public Nhom Nhom
		{
			get
			{
				return this._Nhom.Entity;
			}
			set
			{
				Nhom previousValue = this._Nhom.Entity;
				if (((previousValue != value) 
							|| (this._Nhom.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom.Entity = null;
						previousValue.PhanQuyenNhoms.Remove(this);
					}
					this._Nhom.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNhoms.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(int);
					}
					this.SendPropertyChanged("Nhom");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOSOGOC")]
	public partial class HOSOGOC
	{
		
		private int _OBJECTID;
		
		private string _DBDongHoNuoc;
		
		private string _MaHoSo;
		
		private string _MoTa;
		
		private System.Data.Linq.Binary _DataBlob;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
		private string _NguoiCapNhat;
		
		private string _LoaiFile;
		
		private string _TenHoSo;
		
		public HOSOGOC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJECTID", DbType="Int NOT NULL")]
		public int OBJECTID
		{
			get
			{
				return this._OBJECTID;
			}
			set
			{
				if ((this._OBJECTID != value))
				{
					this._OBJECTID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBDongHoNuoc", DbType="NVarChar(11)")]
		public string DBDongHoNuoc
		{
			get
			{
				return this._DBDongHoNuoc;
			}
			set
			{
				if ((this._DBDongHoNuoc != value))
				{
					this._DBDongHoNuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoSo", DbType="NVarChar(20)")]
		public string MaHoSo
		{
			get
			{
				return this._MaHoSo;
			}
			set
			{
				if ((this._MaHoSo != value))
				{
					this._MaHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(200)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataBlob", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DataBlob
		{
			get
			{
				return this._DataBlob;
			}
			set
			{
				if ((this._DataBlob != value))
				{
					this._DataBlob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime2")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this._NgayCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiCapNhat", DbType="NVarChar(50)")]
		public string NguoiCapNhat
		{
			get
			{
				return this._NguoiCapNhat;
			}
			set
			{
				if ((this._NguoiCapNhat != value))
				{
					this._NguoiCapNhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiFile", DbType="NVarChar(10)")]
		public string LoaiFile
		{
			get
			{
				return this._LoaiFile;
			}
			set
			{
				if ((this._LoaiFile != value))
				{
					this._LoaiFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHoSo", DbType="NVarChar(100)")]
		public string TenHoSo
		{
			get
			{
				return this._TenHoSo;
			}
			set
			{
				if ((this._TenHoSo != value))
				{
					this._TenHoSo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTiepNhan")]
	public partial class LoaiTiepNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLoai;
		
		private string _LoaiKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnLoaiKHChanging(string value);
    partial void OnLoaiKHChanged();
    #endregion
		
		public LoaiTiepNhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="VarChar(50)")]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this.OnLoaiKHChanging(value);
					this.SendPropertyChanging();
					this._LoaiKH = value;
					this.SendPropertyChanged("LoaiKH");
					this.OnLoaiKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TiepNhan")]
	public partial class TiepNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LoaiTN;
		
		private string _SoHoSo;
		
		private string _DanhBo;
		
		private string _DienThoai;
		
		private string _TenKH;
		
		private string _SoNha;
		
		private string _TenDuong;
		
		private string _Phuong;
		
		private string _Quan;
		
		private string _LoaiHs;
		
		private System.Nullable<System.DateTime> _NgayNhan;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _ChuyenHS;
		
		private string _DonViChuyen;
		
		private System.Nullable<System.DateTime> _NgayChuyen;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiTNChanging(string value);
    partial void OnLoaiTNChanged();
    partial void OnSoHoSoChanging(string value);
    partial void OnSoHoSoChanged();
    partial void OnDanhBoChanging(string value);
    partial void OnDanhBoChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSoNhaChanging(string value);
    partial void OnSoNhaChanged();
    partial void OnTenDuongChanging(string value);
    partial void OnTenDuongChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnQuanChanging(string value);
    partial void OnQuanChanged();
    partial void OnLoaiHsChanging(string value);
    partial void OnLoaiHsChanged();
    partial void OnNgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnChuyenHSChanging(System.Nullable<bool> value);
    partial void OnChuyenHSChanged();
    partial void OnDonViChuyenChanging(string value);
    partial void OnDonViChuyenChanged();
    partial void OnNgayChuyenChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(string value);
    partial void OnModifyByChanged();
    #endregion
		
		public TiepNhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTN", DbType="VarChar(50)")]
		public string LoaiTN
		{
			get
			{
				return this._LoaiTN;
			}
			set
			{
				if ((this._LoaiTN != value))
				{
					this.OnLoaiTNChanging(value);
					this.SendPropertyChanging();
					this._LoaiTN = value;
					this.SendPropertyChanged("LoaiTN");
					this.OnLoaiTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoSo", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHoSo
		{
			get
			{
				return this._SoHoSo;
			}
			set
			{
				if ((this._SoHoSo != value))
				{
					this.OnSoHoSoChanging(value);
					this.SendPropertyChanging();
					this._SoHoSo = value;
					this.SendPropertyChanged("SoHoSo");
					this.OnSoHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="VarChar(50)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this.OnDanhBoChanging(value);
					this.SendPropertyChanging();
					this._DanhBo = value;
					this.SendPropertyChanged("DanhBo");
					this.OnDanhBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(150)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNha", DbType="NVarChar(150)")]
		public string SoNha
		{
			get
			{
				return this._SoNha;
			}
			set
			{
				if ((this._SoNha != value))
				{
					this.OnSoNhaChanging(value);
					this.SendPropertyChanging();
					this._SoNha = value;
					this.SendPropertyChanged("SoNha");
					this.OnSoNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuong", DbType="NVarChar(150)")]
		public string TenDuong
		{
			get
			{
				return this._TenDuong;
			}
			set
			{
				if ((this._TenDuong != value))
				{
					this.OnTenDuongChanging(value);
					this.SendPropertyChanging();
					this._TenDuong = value;
					this.SendPropertyChanged("TenDuong");
					this.OnTenDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NVarChar(50)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="NVarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this.OnQuanChanging(value);
					this.SendPropertyChanging();
					this._Quan = value;
					this.SendPropertyChanged("Quan");
					this.OnQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHs", DbType="VarChar(50)")]
		public string LoaiHs
		{
			get
			{
				return this._LoaiHs;
			}
			set
			{
				if ((this._LoaiHs != value))
				{
					this.OnLoaiHsChanging(value);
					this.SendPropertyChanging();
					this._LoaiHs = value;
					this.SendPropertyChanged("LoaiHs");
					this.OnLoaiHsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhan
		{
			get
			{
				return this._NgayNhan;
			}
			set
			{
				if ((this._NgayNhan != value))
				{
					this.OnNgayNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayNhan = value;
					this.SendPropertyChanged("NgayNhan");
					this.OnNgayNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenHS", DbType="Bit")]
		public System.Nullable<bool> ChuyenHS
		{
			get
			{
				return this._ChuyenHS;
			}
			set
			{
				if ((this._ChuyenHS != value))
				{
					this.OnChuyenHSChanging(value);
					this.SendPropertyChanging();
					this._ChuyenHS = value;
					this.SendPropertyChanged("ChuyenHS");
					this.OnChuyenHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViChuyen", DbType="NChar(10)")]
		public string DonViChuyen
		{
			get
			{
				return this._DonViChuyen;
			}
			set
			{
				if ((this._DonViChuyen != value))
				{
					this.OnDonViChuyenChanging(value);
					this.SendPropertyChanging();
					this._DonViChuyen = value;
					this.SendPropertyChanged("DonViChuyen");
					this.OnDonViChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyen", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyen
		{
			get
			{
				return this._NgayChuyen;
			}
			set
			{
				if ((this._NgayChuyen != value))
				{
					this.OnNgayChuyenChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyen = value;
					this.SendPropertyChanged("NgayChuyen");
					this.OnNgayChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="NVarChar(50)")]
		public string ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
