#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HOADON_TA")]
	public partial class ThuTienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertTT_KQDongNuoc(TT_KQDongNuoc instance);
    partial void UpdateTT_KQDongNuoc(TT_KQDongNuoc instance);
    partial void DeleteTT_KQDongNuoc(TT_KQDongNuoc instance);
    #endregion
		
		public ThuTienDataContext() : 
				base(global::CallCenter.Properties.Settings.Default.HOADON_TAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThuTienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThuTienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThuTienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThuTienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<TT_KQDongNuoc> TT_KQDongNuocs
		{
			get
			{
				return this.GetTable<TT_KQDongNuoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HOADON;
		
		private System.Nullable<int> _DOT;
		
		private string _DANHBA;
		
		private string _HOPDONG;
		
		private string _TENKH_;
		
		private string _SO_;
		
		private string _DUONG;
		
		private System.Nullable<int> _GB;
		
		private System.Nullable<int> _TILESH;
		
		private System.Nullable<int> _TILEHCSN;
		
		private System.Nullable<int> _TILESX;
		
		private System.Nullable<int> _TILEDV;
		
		private System.Nullable<decimal> _DM;
		
		private string _CODE;
		
		private System.Nullable<decimal> _CSCU;
		
		private System.Nullable<decimal> _CSMOI;
		
		private System.Nullable<int> _SONGAY;
		
		private System.Nullable<decimal> _TIEUTHU;
		
		private System.Nullable<decimal> _TIEUTHUBU;
		
		private System.Nullable<decimal> _TIEUTHUSH;
		
		private System.Nullable<decimal> _TIEUTHUSX;
		
		private System.Nullable<decimal> _TIEUTHUHCSN;
		
		private System.Nullable<decimal> _TIEUTHUDV;
		
		private System.Nullable<decimal> _GIABAN;
		
		private System.Nullable<decimal> _THUE;
		
		private System.Nullable<decimal> _PHI;
		
		private System.Nullable<decimal> _TONGCONG;
		
		private System.Nullable<decimal> _GIABAN_BU;
		
		private System.Nullable<decimal> _THUE_BU;
		
		private System.Nullable<decimal> _PHI_BU;
		
		private System.Nullable<decimal> _TONGCONG_BU;
		
		private decimal _SOPHATHANH;
		
		private string _SOHOADON;
		
		private int _KY;
		
		private string _MA_NHANVIEN;
		
		private System.Nullable<System.DateTime> _NGAYGIAO;
		
		private string _MST;
		
		private System.Nullable<System.DateTime> _NGAYGIAITRACH;
		
		private System.Nullable<System.DateTime> _TUNGAY;
		
		private System.Nullable<System.DateTime> _DENNGAY;
		
		private System.Nullable<System.DateTime> _GIO_TT;
		
		private System.Nullable<int> _NAM;
		
		private System.Nullable<int> _TO_THUNGAN;
		
		private System.Nullable<int> _L_THANHTOAN;
		
		private System.Nullable<int> _FK_DIEUCHINH;
		
		private string _MAY;
		
		private string _STT;
		
		private string _MALOTRINH;
		
		private System.Nullable<short> _DOTCHIA;
		
		private string _MA_NHANVIENGIAI;
		
		private string _MA_NHANVIENTON;
		
		private System.Nullable<System.DateTime> _NGAYGIAOTON;
		
		private System.Nullable<decimal> _PHI_MONUOC;
		
		private System.Nullable<byte> _Pol;
		
		private string _TENKH;
		
		private string _SO;
		
		private System.Nullable<int> _MaNV_HanhThu;
		
		private System.Nullable<int> _MaNV_GiaoTon;
		
		private System.Nullable<int> _MaNV_HanhThuTruoc;
		
		private bool _DangNgan_HanhThu;
		
		private bool _DangNgan_Quay;
		
		private bool _DangNgan_ChuyenKhoan;
		
		private bool _DangNgan_Ton;
		
		private System.Nullable<int> _MaNV_DangNgan;
		
		private bool _Thu2Lan;
		
		private bool _Thu2Lan_ChuyenKhoan;
		
		private bool _Thu2Lan_Tra;
		
		private System.Nullable<System.DateTime> _Thu2Lan_NgayTra;
		
		private string _Thu2Lan_GhiChu;
		
		private bool _ChuyenNoKhoDoi;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		private string _Quan;
		
		private string _Phuong;
		
		private string _CoDH;
		
		private string _MaDMA;
		
		private System.Nullable<int> _TienDu;
		
		private System.Nullable<int> _TienMat;
		
		private string _SoHoaDonCu;
		
		private bool _ChanTienDu;
		
		private System.Nullable<System.DateTime> _NgayChanTienDu;
		
		private string _HIEULUC;
		
		private string _NAMLD;
		
		private string _HIEUDH;
		
		private bool _KhoaTienDu;
		
		private string _SoThanDHN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HOADONChanging(int value);
    partial void OnID_HOADONChanged();
    partial void OnDOTChanging(System.Nullable<int> value);
    partial void OnDOTChanged();
    partial void OnDANHBAChanging(string value);
    partial void OnDANHBAChanged();
    partial void OnHOPDONGChanging(string value);
    partial void OnHOPDONGChanged();
    partial void OnTENKH_Changing(string value);
    partial void OnTENKH_Changed();
    partial void OnSO_Changing(string value);
    partial void OnSO_Changed();
    partial void OnDUONGChanging(string value);
    partial void OnDUONGChanged();
    partial void OnGBChanging(System.Nullable<int> value);
    partial void OnGBChanged();
    partial void OnTILESHChanging(System.Nullable<int> value);
    partial void OnTILESHChanged();
    partial void OnTILEHCSNChanging(System.Nullable<int> value);
    partial void OnTILEHCSNChanged();
    partial void OnTILESXChanging(System.Nullable<int> value);
    partial void OnTILESXChanged();
    partial void OnTILEDVChanging(System.Nullable<int> value);
    partial void OnTILEDVChanged();
    partial void OnDMChanging(System.Nullable<decimal> value);
    partial void OnDMChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnCSCUChanging(System.Nullable<decimal> value);
    partial void OnCSCUChanged();
    partial void OnCSMOIChanging(System.Nullable<decimal> value);
    partial void OnCSMOIChanged();
    partial void OnSONGAYChanging(System.Nullable<int> value);
    partial void OnSONGAYChanged();
    partial void OnTIEUTHUChanging(System.Nullable<decimal> value);
    partial void OnTIEUTHUChanged();
    partial void OnTIEUTHUBUChanging(System.Nullable<decimal> value);
    partial void OnTIEUTHUBUChanged();
    partial void OnTIEUTHUSHChanging(System.Nullable<decimal> value);
    partial void OnTIEUTHUSHChanged();
    partial void OnTIEUTHUSXChanging(System.Nullable<decimal> value);
    partial void OnTIEUTHUSXChanged();
    partial void OnTIEUTHUHCSNChanging(System.Nullable<decimal> value);
    partial void OnTIEUTHUHCSNChanged();
    partial void OnTIEUTHUDVChanging(System.Nullable<decimal> value);
    partial void OnTIEUTHUDVChanged();
    partial void OnGIABANChanging(System.Nullable<decimal> value);
    partial void OnGIABANChanged();
    partial void OnTHUEChanging(System.Nullable<decimal> value);
    partial void OnTHUEChanged();
    partial void OnPHIChanging(System.Nullable<decimal> value);
    partial void OnPHIChanged();
    partial void OnTONGCONGChanging(System.Nullable<decimal> value);
    partial void OnTONGCONGChanged();
    partial void OnGIABAN_BUChanging(System.Nullable<decimal> value);
    partial void OnGIABAN_BUChanged();
    partial void OnTHUE_BUChanging(System.Nullable<decimal> value);
    partial void OnTHUE_BUChanged();
    partial void OnPHI_BUChanging(System.Nullable<decimal> value);
    partial void OnPHI_BUChanged();
    partial void OnTONGCONG_BUChanging(System.Nullable<decimal> value);
    partial void OnTONGCONG_BUChanged();
    partial void OnSOPHATHANHChanging(decimal value);
    partial void OnSOPHATHANHChanged();
    partial void OnSOHOADONChanging(string value);
    partial void OnSOHOADONChanged();
    partial void OnKYChanging(int value);
    partial void OnKYChanged();
    partial void OnMA_NHANVIENChanging(string value);
    partial void OnMA_NHANVIENChanged();
    partial void OnNGAYGIAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOChanged();
    partial void OnMSTChanging(string value);
    partial void OnMSTChanged();
    partial void OnNGAYGIAITRACHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAITRACHChanged();
    partial void OnTUNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnTUNGAYChanged();
    partial void OnDENNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnDENNGAYChanged();
    partial void OnGIO_TTChanging(System.Nullable<System.DateTime> value);
    partial void OnGIO_TTChanged();
    partial void OnNAMChanging(System.Nullable<int> value);
    partial void OnNAMChanged();
    partial void OnTO_THUNGANChanging(System.Nullable<int> value);
    partial void OnTO_THUNGANChanged();
    partial void OnL_THANHTOANChanging(System.Nullable<int> value);
    partial void OnL_THANHTOANChanged();
    partial void OnFK_DIEUCHINHChanging(System.Nullable<int> value);
    partial void OnFK_DIEUCHINHChanged();
    partial void OnMAYChanging(string value);
    partial void OnMAYChanged();
    partial void OnSTTChanging(string value);
    partial void OnSTTChanged();
    partial void OnMALOTRINHChanging(string value);
    partial void OnMALOTRINHChanged();
    partial void OnDOTCHIAChanging(System.Nullable<short> value);
    partial void OnDOTCHIAChanged();
    partial void OnMA_NHANVIENGIAIChanging(string value);
    partial void OnMA_NHANVIENGIAIChanged();
    partial void OnMA_NHANVIENTONChanging(string value);
    partial void OnMA_NHANVIENTONChanged();
    partial void OnNGAYGIAOTONChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOTONChanged();
    partial void OnPHI_MONUOCChanging(System.Nullable<decimal> value);
    partial void OnPHI_MONUOCChanged();
    partial void OnPolChanging(System.Nullable<byte> value);
    partial void OnPolChanged();
    partial void OnTENKHChanging(string value);
    partial void OnTENKHChanged();
    partial void OnSOChanging(string value);
    partial void OnSOChanged();
    partial void OnMaNV_HanhThuChanging(System.Nullable<int> value);
    partial void OnMaNV_HanhThuChanged();
    partial void OnMaNV_GiaoTonChanging(System.Nullable<int> value);
    partial void OnMaNV_GiaoTonChanged();
    partial void OnMaNV_HanhThuTruocChanging(System.Nullable<int> value);
    partial void OnMaNV_HanhThuTruocChanged();
    partial void OnDangNgan_HanhThuChanging(bool value);
    partial void OnDangNgan_HanhThuChanged();
    partial void OnDangNgan_QuayChanging(bool value);
    partial void OnDangNgan_QuayChanged();
    partial void OnDangNgan_ChuyenKhoanChanging(bool value);
    partial void OnDangNgan_ChuyenKhoanChanged();
    partial void OnDangNgan_TonChanging(bool value);
    partial void OnDangNgan_TonChanged();
    partial void OnMaNV_DangNganChanging(System.Nullable<int> value);
    partial void OnMaNV_DangNganChanged();
    partial void OnThu2LanChanging(bool value);
    partial void OnThu2LanChanged();
    partial void OnThu2Lan_ChuyenKhoanChanging(bool value);
    partial void OnThu2Lan_ChuyenKhoanChanged();
    partial void OnThu2Lan_TraChanging(bool value);
    partial void OnThu2Lan_TraChanged();
    partial void OnThu2Lan_NgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnThu2Lan_NgayTraChanged();
    partial void OnThu2Lan_GhiChuChanging(string value);
    partial void OnThu2Lan_GhiChuChanged();
    partial void OnChuyenNoKhoDoiChanging(bool value);
    partial void OnChuyenNoKhoDoiChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    partial void OnQuanChanging(string value);
    partial void OnQuanChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnCoDHChanging(string value);
    partial void OnCoDHChanged();
    partial void OnMaDMAChanging(string value);
    partial void OnMaDMAChanged();
    partial void OnTienDuChanging(System.Nullable<int> value);
    partial void OnTienDuChanged();
    partial void OnTienMatChanging(System.Nullable<int> value);
    partial void OnTienMatChanged();
    partial void OnSoHoaDonCuChanging(string value);
    partial void OnSoHoaDonCuChanged();
    partial void OnChanTienDuChanging(bool value);
    partial void OnChanTienDuChanged();
    partial void OnNgayChanTienDuChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChanTienDuChanged();
    partial void OnHIEULUCChanging(string value);
    partial void OnHIEULUCChanged();
    partial void OnNAMLDChanging(string value);
    partial void OnNAMLDChanged();
    partial void OnHIEUDHChanging(string value);
    partial void OnHIEUDHChanged();
    partial void OnKhoaTienDuChanging(bool value);
    partial void OnKhoaTienDuChanged();
    partial void OnSoThanDHNChanging(string value);
    partial void OnSoThanDHNChanged();
    #endregion
		
		public HOADON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HOADON", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HOADON
		{
			get
			{
				return this._ID_HOADON;
			}
			set
			{
				if ((this._ID_HOADON != value))
				{
					this.OnID_HOADONChanging(value);
					this.SendPropertyChanging();
					this._ID_HOADON = value;
					this.SendPropertyChanged("ID_HOADON");
					this.OnID_HOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOT", DbType="Int")]
		public System.Nullable<int> DOT
		{
			get
			{
				return this._DOT;
			}
			set
			{
				if ((this._DOT != value))
				{
					this.OnDOTChanging(value);
					this.SendPropertyChanging();
					this._DOT = value;
					this.SendPropertyChanged("DOT");
					this.OnDOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHBA", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string DANHBA
		{
			get
			{
				return this._DANHBA;
			}
			set
			{
				if ((this._DANHBA != value))
				{
					this.OnDANHBAChanging(value);
					this.SendPropertyChanging();
					this._DANHBA = value;
					this.SendPropertyChanged("DANHBA");
					this.OnDANHBAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOPDONG", DbType="NVarChar(10)")]
		public string HOPDONG
		{
			get
			{
				return this._HOPDONG;
			}
			set
			{
				if ((this._HOPDONG != value))
				{
					this.OnHOPDONGChanging(value);
					this.SendPropertyChanging();
					this._HOPDONG = value;
					this.SendPropertyChanged("HOPDONG");
					this.OnHOPDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH_", DbType="NVarChar(60)")]
		public string TENKH_
		{
			get
			{
				return this._TENKH_;
			}
			set
			{
				if ((this._TENKH_ != value))
				{
					this.OnTENKH_Changing(value);
					this.SendPropertyChanging();
					this._TENKH_ = value;
					this.SendPropertyChanged("TENKH_");
					this.OnTENKH_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_", DbType="NVarChar(50)")]
		public string SO_
		{
			get
			{
				return this._SO_;
			}
			set
			{
				if ((this._SO_ != value))
				{
					this.OnSO_Changing(value);
					this.SendPropertyChanging();
					this._SO_ = value;
					this.SendPropertyChanged("SO_");
					this.OnSO_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUONG", DbType="NVarChar(200)")]
		public string DUONG
		{
			get
			{
				return this._DUONG;
			}
			set
			{
				if ((this._DUONG != value))
				{
					this.OnDUONGChanging(value);
					this.SendPropertyChanging();
					this._DUONG = value;
					this.SendPropertyChanged("DUONG");
					this.OnDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GB", DbType="Int")]
		public System.Nullable<int> GB
		{
			get
			{
				return this._GB;
			}
			set
			{
				if ((this._GB != value))
				{
					this.OnGBChanging(value);
					this.SendPropertyChanging();
					this._GB = value;
					this.SendPropertyChanged("GB");
					this.OnGBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TILESH", DbType="Int")]
		public System.Nullable<int> TILESH
		{
			get
			{
				return this._TILESH;
			}
			set
			{
				if ((this._TILESH != value))
				{
					this.OnTILESHChanging(value);
					this.SendPropertyChanging();
					this._TILESH = value;
					this.SendPropertyChanged("TILESH");
					this.OnTILESHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TILEHCSN", DbType="Int")]
		public System.Nullable<int> TILEHCSN
		{
			get
			{
				return this._TILEHCSN;
			}
			set
			{
				if ((this._TILEHCSN != value))
				{
					this.OnTILEHCSNChanging(value);
					this.SendPropertyChanging();
					this._TILEHCSN = value;
					this.SendPropertyChanged("TILEHCSN");
					this.OnTILEHCSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TILESX", DbType="Int")]
		public System.Nullable<int> TILESX
		{
			get
			{
				return this._TILESX;
			}
			set
			{
				if ((this._TILESX != value))
				{
					this.OnTILESXChanging(value);
					this.SendPropertyChanging();
					this._TILESX = value;
					this.SendPropertyChanged("TILESX");
					this.OnTILESXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TILEDV", DbType="Int")]
		public System.Nullable<int> TILEDV
		{
			get
			{
				return this._TILEDV;
			}
			set
			{
				if ((this._TILEDV != value))
				{
					this.OnTILEDVChanging(value);
					this.SendPropertyChanging();
					this._TILEDV = value;
					this.SendPropertyChanged("TILEDV");
					this.OnTILEDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DM
		{
			get
			{
				return this._DM;
			}
			set
			{
				if ((this._DM != value))
				{
					this.OnDMChanging(value);
					this.SendPropertyChanging();
					this._DM = value;
					this.SendPropertyChanged("DM");
					this.OnDMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(2)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CSCU
		{
			get
			{
				return this._CSCU;
			}
			set
			{
				if ((this._CSCU != value))
				{
					this.OnCSCUChanging(value);
					this.SendPropertyChanging();
					this._CSCU = value;
					this.SendPropertyChanged("CSCU");
					this.OnCSCUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSMOI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CSMOI
		{
			get
			{
				return this._CSMOI;
			}
			set
			{
				if ((this._CSMOI != value))
				{
					this.OnCSMOIChanging(value);
					this.SendPropertyChanging();
					this._CSMOI = value;
					this.SendPropertyChanged("CSMOI");
					this.OnCSMOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAY", DbType="Int")]
		public System.Nullable<int> SONGAY
		{
			get
			{
				return this._SONGAY;
			}
			set
			{
				if ((this._SONGAY != value))
				{
					this.OnSONGAYChanging(value);
					this.SendPropertyChanging();
					this._SONGAY = value;
					this.SendPropertyChanged("SONGAY");
					this.OnSONGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUTHU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIEUTHU
		{
			get
			{
				return this._TIEUTHU;
			}
			set
			{
				if ((this._TIEUTHU != value))
				{
					this.OnTIEUTHUChanging(value);
					this.SendPropertyChanging();
					this._TIEUTHU = value;
					this.SendPropertyChanged("TIEUTHU");
					this.OnTIEUTHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUTHUBU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIEUTHUBU
		{
			get
			{
				return this._TIEUTHUBU;
			}
			set
			{
				if ((this._TIEUTHUBU != value))
				{
					this.OnTIEUTHUBUChanging(value);
					this.SendPropertyChanging();
					this._TIEUTHUBU = value;
					this.SendPropertyChanged("TIEUTHUBU");
					this.OnTIEUTHUBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUTHUSH", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIEUTHUSH
		{
			get
			{
				return this._TIEUTHUSH;
			}
			set
			{
				if ((this._TIEUTHUSH != value))
				{
					this.OnTIEUTHUSHChanging(value);
					this.SendPropertyChanging();
					this._TIEUTHUSH = value;
					this.SendPropertyChanged("TIEUTHUSH");
					this.OnTIEUTHUSHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUTHUSX", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIEUTHUSX
		{
			get
			{
				return this._TIEUTHUSX;
			}
			set
			{
				if ((this._TIEUTHUSX != value))
				{
					this.OnTIEUTHUSXChanging(value);
					this.SendPropertyChanging();
					this._TIEUTHUSX = value;
					this.SendPropertyChanged("TIEUTHUSX");
					this.OnTIEUTHUSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUTHUHCSN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIEUTHUHCSN
		{
			get
			{
				return this._TIEUTHUHCSN;
			}
			set
			{
				if ((this._TIEUTHUHCSN != value))
				{
					this.OnTIEUTHUHCSNChanging(value);
					this.SendPropertyChanging();
					this._TIEUTHUHCSN = value;
					this.SendPropertyChanged("TIEUTHUHCSN");
					this.OnTIEUTHUHCSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUTHUDV", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TIEUTHUDV
		{
			get
			{
				return this._TIEUTHUDV;
			}
			set
			{
				if ((this._TIEUTHUDV != value))
				{
					this.OnTIEUTHUDVChanging(value);
					this.SendPropertyChanging();
					this._TIEUTHUDV = value;
					this.SendPropertyChanged("TIEUTHUDV");
					this.OnTIEUTHUDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> THUE
		{
			get
			{
				return this._THUE;
			}
			set
			{
				if ((this._THUE != value))
				{
					this.OnTHUEChanging(value);
					this.SendPropertyChanging();
					this._THUE = value;
					this.SendPropertyChanged("THUE");
					this.OnTHUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PHI
		{
			get
			{
				return this._PHI;
			}
			set
			{
				if ((this._PHI != value))
				{
					this.OnPHIChanging(value);
					this.SendPropertyChanging();
					this._PHI = value;
					this.SendPropertyChanged("PHI");
					this.OnPHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCONG", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONGCONG
		{
			get
			{
				return this._TONGCONG;
			}
			set
			{
				if ((this._TONGCONG != value))
				{
					this.OnTONGCONGChanging(value);
					this.SendPropertyChanging();
					this._TONGCONG = value;
					this.SendPropertyChanged("TONGCONG");
					this.OnTONGCONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN_BU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIABAN_BU
		{
			get
			{
				return this._GIABAN_BU;
			}
			set
			{
				if ((this._GIABAN_BU != value))
				{
					this.OnGIABAN_BUChanging(value);
					this.SendPropertyChanging();
					this._GIABAN_BU = value;
					this.SendPropertyChanged("GIABAN_BU");
					this.OnGIABAN_BUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THUE_BU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> THUE_BU
		{
			get
			{
				return this._THUE_BU;
			}
			set
			{
				if ((this._THUE_BU != value))
				{
					this.OnTHUE_BUChanging(value);
					this.SendPropertyChanging();
					this._THUE_BU = value;
					this.SendPropertyChanged("THUE_BU");
					this.OnTHUE_BUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHI_BU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PHI_BU
		{
			get
			{
				return this._PHI_BU;
			}
			set
			{
				if ((this._PHI_BU != value))
				{
					this.OnPHI_BUChanging(value);
					this.SendPropertyChanging();
					this._PHI_BU = value;
					this.SendPropertyChanged("PHI_BU");
					this.OnPHI_BUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGCONG_BU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONGCONG_BU
		{
			get
			{
				return this._TONGCONG_BU;
			}
			set
			{
				if ((this._TONGCONG_BU != value))
				{
					this.OnTONGCONG_BUChanging(value);
					this.SendPropertyChanging();
					this._TONGCONG_BU = value;
					this.SendPropertyChanged("TONGCONG_BU");
					this.OnTONGCONG_BUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPHATHANH", DbType="Decimal(18,0) NOT NULL")]
		public decimal SOPHATHANH
		{
			get
			{
				return this._SOPHATHANH;
			}
			set
			{
				if ((this._SOPHATHANH != value))
				{
					this.OnSOPHATHANHChanging(value);
					this.SendPropertyChanging();
					this._SOPHATHANH = value;
					this.SendPropertyChanged("SOPHATHANH");
					this.OnSOPHATHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOHOADON", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SOHOADON
		{
			get
			{
				return this._SOHOADON;
			}
			set
			{
				if ((this._SOHOADON != value))
				{
					this.OnSOHOADONChanging(value);
					this.SendPropertyChanging();
					this._SOHOADON = value;
					this.SendPropertyChanged("SOHOADON");
					this.OnSOHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KY", DbType="Int NOT NULL")]
		public int KY
		{
			get
			{
				return this._KY;
			}
			set
			{
				if ((this._KY != value))
				{
					this.OnKYChanging(value);
					this.SendPropertyChanging();
					this._KY = value;
					this.SendPropertyChanged("KY");
					this.OnKYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NHANVIEN", DbType="VarChar(10)")]
		public string MA_NHANVIEN
		{
			get
			{
				return this._MA_NHANVIEN;
			}
			set
			{
				if ((this._MA_NHANVIEN != value))
				{
					this.OnMA_NHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MA_NHANVIEN = value;
					this.SendPropertyChanged("MA_NHANVIEN");
					this.OnMA_NHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIAO
		{
			get
			{
				return this._NGAYGIAO;
			}
			set
			{
				if ((this._NGAYGIAO != value))
				{
					this.OnNGAYGIAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAO = value;
					this.SendPropertyChanged("NGAYGIAO");
					this.OnNGAYGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MST", DbType="NVarChar(20)")]
		public string MST
		{
			get
			{
				return this._MST;
			}
			set
			{
				if ((this._MST != value))
				{
					this.OnMSTChanging(value);
					this.SendPropertyChanging();
					this._MST = value;
					this.SendPropertyChanged("MST");
					this.OnMSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAITRACH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIAITRACH
		{
			get
			{
				return this._NGAYGIAITRACH;
			}
			set
			{
				if ((this._NGAYGIAITRACH != value))
				{
					this.OnNGAYGIAITRACHChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAITRACH = value;
					this.SendPropertyChanged("NGAYGIAITRACH");
					this.OnNGAYGIAITRACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUNGAY", DbType="DateTime")]
		public System.Nullable<System.DateTime> TUNGAY
		{
			get
			{
				return this._TUNGAY;
			}
			set
			{
				if ((this._TUNGAY != value))
				{
					this.OnTUNGAYChanging(value);
					this.SendPropertyChanging();
					this._TUNGAY = value;
					this.SendPropertyChanged("TUNGAY");
					this.OnTUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="DateTime")]
		public System.Nullable<System.DateTime> DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIO_TT", DbType="DateTime")]
		public System.Nullable<System.DateTime> GIO_TT
		{
			get
			{
				return this._GIO_TT;
			}
			set
			{
				if ((this._GIO_TT != value))
				{
					this.OnGIO_TTChanging(value);
					this.SendPropertyChanging();
					this._GIO_TT = value;
					this.SendPropertyChanged("GIO_TT");
					this.OnGIO_TTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAM", DbType="Int")]
		public System.Nullable<int> NAM
		{
			get
			{
				return this._NAM;
			}
			set
			{
				if ((this._NAM != value))
				{
					this.OnNAMChanging(value);
					this.SendPropertyChanging();
					this._NAM = value;
					this.SendPropertyChanged("NAM");
					this.OnNAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TO_THUNGAN", DbType="Int")]
		public System.Nullable<int> TO_THUNGAN
		{
			get
			{
				return this._TO_THUNGAN;
			}
			set
			{
				if ((this._TO_THUNGAN != value))
				{
					this.OnTO_THUNGANChanging(value);
					this.SendPropertyChanging();
					this._TO_THUNGAN = value;
					this.SendPropertyChanged("TO_THUNGAN");
					this.OnTO_THUNGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_THANHTOAN", DbType="Int")]
		public System.Nullable<int> L_THANHTOAN
		{
			get
			{
				return this._L_THANHTOAN;
			}
			set
			{
				if ((this._L_THANHTOAN != value))
				{
					this.OnL_THANHTOANChanging(value);
					this.SendPropertyChanging();
					this._L_THANHTOAN = value;
					this.SendPropertyChanged("L_THANHTOAN");
					this.OnL_THANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_DIEUCHINH", DbType="Int")]
		public System.Nullable<int> FK_DIEUCHINH
		{
			get
			{
				return this._FK_DIEUCHINH;
			}
			set
			{
				if ((this._FK_DIEUCHINH != value))
				{
					this.OnFK_DIEUCHINHChanging(value);
					this.SendPropertyChanging();
					this._FK_DIEUCHINH = value;
					this.SendPropertyChanged("FK_DIEUCHINH");
					this.OnFK_DIEUCHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAY", DbType="NChar(2)")]
		public string MAY
		{
			get
			{
				return this._MAY;
			}
			set
			{
				if ((this._MAY != value))
				{
					this.OnMAYChanging(value);
					this.SendPropertyChanging();
					this._MAY = value;
					this.SendPropertyChanged("MAY");
					this.OnMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="NChar(5)")]
		public string STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOTRINH", DbType="NChar(10)")]
		public string MALOTRINH
		{
			get
			{
				return this._MALOTRINH;
			}
			set
			{
				if ((this._MALOTRINH != value))
				{
					this.OnMALOTRINHChanging(value);
					this.SendPropertyChanging();
					this._MALOTRINH = value;
					this.SendPropertyChanged("MALOTRINH");
					this.OnMALOTRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOTCHIA", DbType="SmallInt")]
		public System.Nullable<short> DOTCHIA
		{
			get
			{
				return this._DOTCHIA;
			}
			set
			{
				if ((this._DOTCHIA != value))
				{
					this.OnDOTCHIAChanging(value);
					this.SendPropertyChanging();
					this._DOTCHIA = value;
					this.SendPropertyChanged("DOTCHIA");
					this.OnDOTCHIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NHANVIENGIAI", DbType="NChar(10)")]
		public string MA_NHANVIENGIAI
		{
			get
			{
				return this._MA_NHANVIENGIAI;
			}
			set
			{
				if ((this._MA_NHANVIENGIAI != value))
				{
					this.OnMA_NHANVIENGIAIChanging(value);
					this.SendPropertyChanging();
					this._MA_NHANVIENGIAI = value;
					this.SendPropertyChanged("MA_NHANVIENGIAI");
					this.OnMA_NHANVIENGIAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NHANVIENTON", DbType="NChar(10)")]
		public string MA_NHANVIENTON
		{
			get
			{
				return this._MA_NHANVIENTON;
			}
			set
			{
				if ((this._MA_NHANVIENTON != value))
				{
					this.OnMA_NHANVIENTONChanging(value);
					this.SendPropertyChanging();
					this._MA_NHANVIENTON = value;
					this.SendPropertyChanged("MA_NHANVIENTON");
					this.OnMA_NHANVIENTONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAOTON", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYGIAOTON
		{
			get
			{
				return this._NGAYGIAOTON;
			}
			set
			{
				if ((this._NGAYGIAOTON != value))
				{
					this.OnNGAYGIAOTONChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAOTON = value;
					this.SendPropertyChanged("NGAYGIAOTON");
					this.OnNGAYGIAOTONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHI_MONUOC", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PHI_MONUOC
		{
			get
			{
				return this._PHI_MONUOC;
			}
			set
			{
				if ((this._PHI_MONUOC != value))
				{
					this.OnPHI_MONUOCChanging(value);
					this.SendPropertyChanging();
					this._PHI_MONUOC = value;
					this.SendPropertyChanged("PHI_MONUOC");
					this.OnPHI_MONUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pol", DbType="TinyInt")]
		public System.Nullable<byte> Pol
		{
			get
			{
				return this._Pol;
			}
			set
			{
				if ((this._Pol != value))
				{
					this.OnPolChanging(value);
					this.SendPropertyChanging();
					this._Pol = value;
					this.SendPropertyChanged("Pol");
					this.OnPolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH", DbType="VarChar(250)")]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this.OnTENKHChanging(value);
					this.SendPropertyChanging();
					this._TENKH = value;
					this.SendPropertyChanged("TENKH");
					this.OnTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO", DbType="VarChar(200)")]
		public string SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				if ((this._SO != value))
				{
					this.OnSOChanging(value);
					this.SendPropertyChanging();
					this._SO = value;
					this.SendPropertyChanged("SO");
					this.OnSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV_HanhThu", DbType="Int")]
		public System.Nullable<int> MaNV_HanhThu
		{
			get
			{
				return this._MaNV_HanhThu;
			}
			set
			{
				if ((this._MaNV_HanhThu != value))
				{
					this.OnMaNV_HanhThuChanging(value);
					this.SendPropertyChanging();
					this._MaNV_HanhThu = value;
					this.SendPropertyChanged("MaNV_HanhThu");
					this.OnMaNV_HanhThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV_GiaoTon", DbType="Int")]
		public System.Nullable<int> MaNV_GiaoTon
		{
			get
			{
				return this._MaNV_GiaoTon;
			}
			set
			{
				if ((this._MaNV_GiaoTon != value))
				{
					this.OnMaNV_GiaoTonChanging(value);
					this.SendPropertyChanging();
					this._MaNV_GiaoTon = value;
					this.SendPropertyChanged("MaNV_GiaoTon");
					this.OnMaNV_GiaoTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV_HanhThuTruoc", DbType="Int")]
		public System.Nullable<int> MaNV_HanhThuTruoc
		{
			get
			{
				return this._MaNV_HanhThuTruoc;
			}
			set
			{
				if ((this._MaNV_HanhThuTruoc != value))
				{
					this.OnMaNV_HanhThuTruocChanging(value);
					this.SendPropertyChanging();
					this._MaNV_HanhThuTruoc = value;
					this.SendPropertyChanged("MaNV_HanhThuTruoc");
					this.OnMaNV_HanhThuTruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangNgan_HanhThu", DbType="Bit NOT NULL")]
		public bool DangNgan_HanhThu
		{
			get
			{
				return this._DangNgan_HanhThu;
			}
			set
			{
				if ((this._DangNgan_HanhThu != value))
				{
					this.OnDangNgan_HanhThuChanging(value);
					this.SendPropertyChanging();
					this._DangNgan_HanhThu = value;
					this.SendPropertyChanged("DangNgan_HanhThu");
					this.OnDangNgan_HanhThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangNgan_Quay", DbType="Bit NOT NULL")]
		public bool DangNgan_Quay
		{
			get
			{
				return this._DangNgan_Quay;
			}
			set
			{
				if ((this._DangNgan_Quay != value))
				{
					this.OnDangNgan_QuayChanging(value);
					this.SendPropertyChanging();
					this._DangNgan_Quay = value;
					this.SendPropertyChanged("DangNgan_Quay");
					this.OnDangNgan_QuayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangNgan_ChuyenKhoan", DbType="Bit NOT NULL")]
		public bool DangNgan_ChuyenKhoan
		{
			get
			{
				return this._DangNgan_ChuyenKhoan;
			}
			set
			{
				if ((this._DangNgan_ChuyenKhoan != value))
				{
					this.OnDangNgan_ChuyenKhoanChanging(value);
					this.SendPropertyChanging();
					this._DangNgan_ChuyenKhoan = value;
					this.SendPropertyChanged("DangNgan_ChuyenKhoan");
					this.OnDangNgan_ChuyenKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangNgan_Ton", DbType="Bit NOT NULL")]
		public bool DangNgan_Ton
		{
			get
			{
				return this._DangNgan_Ton;
			}
			set
			{
				if ((this._DangNgan_Ton != value))
				{
					this.OnDangNgan_TonChanging(value);
					this.SendPropertyChanging();
					this._DangNgan_Ton = value;
					this.SendPropertyChanged("DangNgan_Ton");
					this.OnDangNgan_TonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV_DangNgan", DbType="Int")]
		public System.Nullable<int> MaNV_DangNgan
		{
			get
			{
				return this._MaNV_DangNgan;
			}
			set
			{
				if ((this._MaNV_DangNgan != value))
				{
					this.OnMaNV_DangNganChanging(value);
					this.SendPropertyChanging();
					this._MaNV_DangNgan = value;
					this.SendPropertyChanged("MaNV_DangNgan");
					this.OnMaNV_DangNganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu2Lan", DbType="Bit NOT NULL")]
		public bool Thu2Lan
		{
			get
			{
				return this._Thu2Lan;
			}
			set
			{
				if ((this._Thu2Lan != value))
				{
					this.OnThu2LanChanging(value);
					this.SendPropertyChanging();
					this._Thu2Lan = value;
					this.SendPropertyChanged("Thu2Lan");
					this.OnThu2LanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu2Lan_ChuyenKhoan", DbType="Bit NOT NULL")]
		public bool Thu2Lan_ChuyenKhoan
		{
			get
			{
				return this._Thu2Lan_ChuyenKhoan;
			}
			set
			{
				if ((this._Thu2Lan_ChuyenKhoan != value))
				{
					this.OnThu2Lan_ChuyenKhoanChanging(value);
					this.SendPropertyChanging();
					this._Thu2Lan_ChuyenKhoan = value;
					this.SendPropertyChanged("Thu2Lan_ChuyenKhoan");
					this.OnThu2Lan_ChuyenKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu2Lan_Tra", DbType="Bit NOT NULL")]
		public bool Thu2Lan_Tra
		{
			get
			{
				return this._Thu2Lan_Tra;
			}
			set
			{
				if ((this._Thu2Lan_Tra != value))
				{
					this.OnThu2Lan_TraChanging(value);
					this.SendPropertyChanging();
					this._Thu2Lan_Tra = value;
					this.SendPropertyChanged("Thu2Lan_Tra");
					this.OnThu2Lan_TraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu2Lan_NgayTra", DbType="DateTime")]
		public System.Nullable<System.DateTime> Thu2Lan_NgayTra
		{
			get
			{
				return this._Thu2Lan_NgayTra;
			}
			set
			{
				if ((this._Thu2Lan_NgayTra != value))
				{
					this.OnThu2Lan_NgayTraChanging(value);
					this.SendPropertyChanging();
					this._Thu2Lan_NgayTra = value;
					this.SendPropertyChanged("Thu2Lan_NgayTra");
					this.OnThu2Lan_NgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu2Lan_GhiChu", DbType="NVarChar(MAX)")]
		public string Thu2Lan_GhiChu
		{
			get
			{
				return this._Thu2Lan_GhiChu;
			}
			set
			{
				if ((this._Thu2Lan_GhiChu != value))
				{
					this.OnThu2Lan_GhiChuChanging(value);
					this.SendPropertyChanging();
					this._Thu2Lan_GhiChu = value;
					this.SendPropertyChanged("Thu2Lan_GhiChu");
					this.OnThu2Lan_GhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenNoKhoDoi", DbType="Bit NOT NULL")]
		public bool ChuyenNoKhoDoi
		{
			get
			{
				return this._ChuyenNoKhoDoi;
			}
			set
			{
				if ((this._ChuyenNoKhoDoi != value))
				{
					this.OnChuyenNoKhoDoiChanging(value);
					this.SendPropertyChanging();
					this._ChuyenNoKhoDoi = value;
					this.SendPropertyChanged("ChuyenNoKhoDoi");
					this.OnChuyenNoKhoDoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="NVarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this.OnQuanChanging(value);
					this.SendPropertyChanging();
					this._Quan = value;
					this.SendPropertyChanged("Quan");
					this.OnQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NVarChar(50)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoDH", DbType="NVarChar(50)")]
		public string CoDH
		{
			get
			{
				return this._CoDH;
			}
			set
			{
				if ((this._CoDH != value))
				{
					this.OnCoDHChanging(value);
					this.SendPropertyChanging();
					this._CoDH = value;
					this.SendPropertyChanged("CoDH");
					this.OnCoDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDMA", DbType="NVarChar(50)")]
		public string MaDMA
		{
			get
			{
				return this._MaDMA;
			}
			set
			{
				if ((this._MaDMA != value))
				{
					this.OnMaDMAChanging(value);
					this.SendPropertyChanging();
					this._MaDMA = value;
					this.SendPropertyChanged("MaDMA");
					this.OnMaDMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienDu", DbType="Int")]
		public System.Nullable<int> TienDu
		{
			get
			{
				return this._TienDu;
			}
			set
			{
				if ((this._TienDu != value))
				{
					this.OnTienDuChanging(value);
					this.SendPropertyChanging();
					this._TienDu = value;
					this.SendPropertyChanged("TienDu");
					this.OnTienDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienMat", DbType="Int")]
		public System.Nullable<int> TienMat
		{
			get
			{
				return this._TienMat;
			}
			set
			{
				if ((this._TienMat != value))
				{
					this.OnTienMatChanging(value);
					this.SendPropertyChanging();
					this._TienMat = value;
					this.SendPropertyChanged("TienMat");
					this.OnTienMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoaDonCu", DbType="NVarChar(20)")]
		public string SoHoaDonCu
		{
			get
			{
				return this._SoHoaDonCu;
			}
			set
			{
				if ((this._SoHoaDonCu != value))
				{
					this.OnSoHoaDonCuChanging(value);
					this.SendPropertyChanging();
					this._SoHoaDonCu = value;
					this.SendPropertyChanged("SoHoaDonCu");
					this.OnSoHoaDonCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChanTienDu", DbType="Bit NOT NULL")]
		public bool ChanTienDu
		{
			get
			{
				return this._ChanTienDu;
			}
			set
			{
				if ((this._ChanTienDu != value))
				{
					this.OnChanTienDuChanging(value);
					this.SendPropertyChanging();
					this._ChanTienDu = value;
					this.SendPropertyChanged("ChanTienDu");
					this.OnChanTienDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChanTienDu", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChanTienDu
		{
			get
			{
				return this._NgayChanTienDu;
			}
			set
			{
				if ((this._NgayChanTienDu != value))
				{
					this.OnNgayChanTienDuChanging(value);
					this.SendPropertyChanging();
					this._NgayChanTienDu = value;
					this.SendPropertyChanged("NgayChanTienDu");
					this.OnNgayChanTienDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEULUC", DbType="NVarChar(50)")]
		public string HIEULUC
		{
			get
			{
				return this._HIEULUC;
			}
			set
			{
				if ((this._HIEULUC != value))
				{
					this.OnHIEULUCChanging(value);
					this.SendPropertyChanging();
					this._HIEULUC = value;
					this.SendPropertyChanged("HIEULUC");
					this.OnHIEULUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMLD", DbType="NVarChar(50)")]
		public string NAMLD
		{
			get
			{
				return this._NAMLD;
			}
			set
			{
				if ((this._NAMLD != value))
				{
					this.OnNAMLDChanging(value);
					this.SendPropertyChanging();
					this._NAMLD = value;
					this.SendPropertyChanged("NAMLD");
					this.OnNAMLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIEUDH", DbType="NVarChar(50)")]
		public string HIEUDH
		{
			get
			{
				return this._HIEUDH;
			}
			set
			{
				if ((this._HIEUDH != value))
				{
					this.OnHIEUDHChanging(value);
					this.SendPropertyChanging();
					this._HIEUDH = value;
					this.SendPropertyChanged("HIEUDH");
					this.OnHIEUDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoaTienDu", DbType="Bit NOT NULL")]
		public bool KhoaTienDu
		{
			get
			{
				return this._KhoaTienDu;
			}
			set
			{
				if ((this._KhoaTienDu != value))
				{
					this.OnKhoaTienDuChanging(value);
					this.SendPropertyChanging();
					this._KhoaTienDu = value;
					this.SendPropertyChanged("KhoaTienDu");
					this.OnKhoaTienDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThanDHN", DbType="VarChar(50)")]
		public string SoThanDHN
		{
			get
			{
				return this._SoThanDHN;
			}
			set
			{
				if ((this._SoThanDHN != value))
				{
					this.OnSoThanDHNChanging(value);
					this.SendPropertyChanging();
					this._SoThanDHN = value;
					this.SendPropertyChanged("SoThanDHN");
					this.OnSoThanDHNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TT_KQDongNuoc")]
	public partial class TT_KQDongNuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKQDN;
		
		private string _DanhBo;
		
		private string _HopDong;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _MLT;
		
		private bool _DongNuoc;
		
		private System.Nullable<System.DateTime> _NgayDN;
		
		private string _Hieu;
		
		private System.Nullable<int> _Co;
		
		private string _SoThan;
		
		private System.Nullable<int> _ChiSoDN;
		
		private string _ChiMatSo;
		
		private string _ChiKhoaGoc;
		
		private string _LyDo;
		
		private string _GhiChu;
		
		private System.Nullable<int> _PhiMoNuoc;
		
		private bool _DongNuoc2;
		
		private System.Nullable<System.DateTime> _NgayDN1;
		
		private System.Nullable<int> _ChiSoDN1;
		
		private bool _DongPhi;
		
		private bool _ChuyenKhoan;
		
		private System.Nullable<System.DateTime> _NgayDongPhi;
		
		private System.Nullable<decimal> _SoPhieuDN;
		
		private System.Nullable<System.DateTime> _NgaySoPhieuDN;
		
		private bool _ChuyenDN;
		
		private System.Nullable<System.DateTime> _NgayChuyenDN;
		
		private System.Nullable<decimal> _SoPhieuDN1;
		
		private System.Nullable<System.DateTime> _NgaySoPhieuDN1;
		
		private bool _ChuyenDN1;
		
		private System.Nullable<System.DateTime> _NgayChuyenDN1;
		
		private bool _TroNgaiMN;
		
		private bool _MoNuoc;
		
		private System.Nullable<System.DateTime> _NgayMN;
		
		private System.Nullable<int> _ChiSoMN;
		
		private System.Nullable<decimal> _SoPhieuMN;
		
		private System.Nullable<System.DateTime> _NgaySoPhieuMN;
		
		private bool _ChuyenMN;
		
		private System.Nullable<System.DateTime> _NgayChuyenMN;
		
		private string _GhiChuTroNgai;
		
		private System.Nullable<decimal> _MaDN;
		
		private bool _DaKy;
		
		private System.Nullable<System.DateTime> _NgayKy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKQDNChanging(int value);
    partial void OnMaKQDNChanged();
    partial void OnDanhBoChanging(string value);
    partial void OnDanhBoChanged();
    partial void OnHopDongChanging(string value);
    partial void OnHopDongChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMLTChanging(string value);
    partial void OnMLTChanged();
    partial void OnDongNuocChanging(bool value);
    partial void OnDongNuocChanged();
    partial void OnNgayDNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDNChanged();
    partial void OnHieuChanging(string value);
    partial void OnHieuChanged();
    partial void OnCoChanging(System.Nullable<int> value);
    partial void OnCoChanged();
    partial void OnSoThanChanging(string value);
    partial void OnSoThanChanged();
    partial void OnChiSoDNChanging(System.Nullable<int> value);
    partial void OnChiSoDNChanged();
    partial void OnChiMatSoChanging(string value);
    partial void OnChiMatSoChanged();
    partial void OnChiKhoaGocChanging(string value);
    partial void OnChiKhoaGocChanged();
    partial void OnLyDoChanging(string value);
    partial void OnLyDoChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnPhiMoNuocChanging(System.Nullable<int> value);
    partial void OnPhiMoNuocChanged();
    partial void OnDongNuoc2Changing(bool value);
    partial void OnDongNuoc2Changed();
    partial void OnNgayDN1Changing(System.Nullable<System.DateTime> value);
    partial void OnNgayDN1Changed();
    partial void OnChiSoDN1Changing(System.Nullable<int> value);
    partial void OnChiSoDN1Changed();
    partial void OnDongPhiChanging(bool value);
    partial void OnDongPhiChanged();
    partial void OnChuyenKhoanChanging(bool value);
    partial void OnChuyenKhoanChanged();
    partial void OnNgayDongPhiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDongPhiChanged();
    partial void OnSoPhieuDNChanging(System.Nullable<decimal> value);
    partial void OnSoPhieuDNChanged();
    partial void OnNgaySoPhieuDNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySoPhieuDNChanged();
    partial void OnChuyenDNChanging(bool value);
    partial void OnChuyenDNChanged();
    partial void OnNgayChuyenDNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenDNChanged();
    partial void OnSoPhieuDN1Changing(System.Nullable<decimal> value);
    partial void OnSoPhieuDN1Changed();
    partial void OnNgaySoPhieuDN1Changing(System.Nullable<System.DateTime> value);
    partial void OnNgaySoPhieuDN1Changed();
    partial void OnChuyenDN1Changing(bool value);
    partial void OnChuyenDN1Changed();
    partial void OnNgayChuyenDN1Changing(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenDN1Changed();
    partial void OnTroNgaiMNChanging(bool value);
    partial void OnTroNgaiMNChanged();
    partial void OnMoNuocChanging(bool value);
    partial void OnMoNuocChanged();
    partial void OnNgayMNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMNChanged();
    partial void OnChiSoMNChanging(System.Nullable<int> value);
    partial void OnChiSoMNChanged();
    partial void OnSoPhieuMNChanging(System.Nullable<decimal> value);
    partial void OnSoPhieuMNChanged();
    partial void OnNgaySoPhieuMNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySoPhieuMNChanged();
    partial void OnChuyenMNChanging(bool value);
    partial void OnChuyenMNChanged();
    partial void OnNgayChuyenMNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenMNChanged();
    partial void OnGhiChuTroNgaiChanging(string value);
    partial void OnGhiChuTroNgaiChanged();
    partial void OnMaDNChanging(System.Nullable<decimal> value);
    partial void OnMaDNChanged();
    partial void OnDaKyChanging(bool value);
    partial void OnDaKyChanged();
    partial void OnNgayKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKyChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public TT_KQDongNuoc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKQDN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKQDN
		{
			get
			{
				return this._MaKQDN;
			}
			set
			{
				if ((this._MaKQDN != value))
				{
					this.OnMaKQDNChanging(value);
					this.SendPropertyChanging();
					this._MaKQDN = value;
					this.SendPropertyChanged("MaKQDN");
					this.OnMaKQDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="VarChar(50)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this.OnDanhBoChanging(value);
					this.SendPropertyChanging();
					this._DanhBo = value;
					this.SendPropertyChanged("DanhBo");
					this.OnDanhBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopDong", DbType="VarChar(50)")]
		public string HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					this.OnHopDongChanging(value);
					this.SendPropertyChanging();
					this._HopDong = value;
					this.SendPropertyChanged("HopDong");
					this.OnHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MLT", DbType="VarChar(50)")]
		public string MLT
		{
			get
			{
				return this._MLT;
			}
			set
			{
				if ((this._MLT != value))
				{
					this.OnMLTChanging(value);
					this.SendPropertyChanging();
					this._MLT = value;
					this.SendPropertyChanged("MLT");
					this.OnMLTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongNuoc", DbType="Bit NOT NULL")]
		public bool DongNuoc
		{
			get
			{
				return this._DongNuoc;
			}
			set
			{
				if ((this._DongNuoc != value))
				{
					this.OnDongNuocChanging(value);
					this.SendPropertyChanging();
					this._DongNuoc = value;
					this.SendPropertyChanged("DongNuoc");
					this.OnDongNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDN
		{
			get
			{
				return this._NgayDN;
			}
			set
			{
				if ((this._NgayDN != value))
				{
					this.OnNgayDNChanging(value);
					this.SendPropertyChanging();
					this._NgayDN = value;
					this.SendPropertyChanged("NgayDN");
					this.OnNgayDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hieu", DbType="NVarChar(50)")]
		public string Hieu
		{
			get
			{
				return this._Hieu;
			}
			set
			{
				if ((this._Hieu != value))
				{
					this.OnHieuChanging(value);
					this.SendPropertyChanging();
					this._Hieu = value;
					this.SendPropertyChanged("Hieu");
					this.OnHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Int")]
		public System.Nullable<int> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThan", DbType="VarChar(50)")]
		public string SoThan
		{
			get
			{
				return this._SoThan;
			}
			set
			{
				if ((this._SoThan != value))
				{
					this.OnSoThanChanging(value);
					this.SendPropertyChanging();
					this._SoThan = value;
					this.SendPropertyChanged("SoThan");
					this.OnSoThanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoDN", DbType="Int")]
		public System.Nullable<int> ChiSoDN
		{
			get
			{
				return this._ChiSoDN;
			}
			set
			{
				if ((this._ChiSoDN != value))
				{
					this.OnChiSoDNChanging(value);
					this.SendPropertyChanging();
					this._ChiSoDN = value;
					this.SendPropertyChanged("ChiSoDN");
					this.OnChiSoDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiMatSo", DbType="NVarChar(50)")]
		public string ChiMatSo
		{
			get
			{
				return this._ChiMatSo;
			}
			set
			{
				if ((this._ChiMatSo != value))
				{
					this.OnChiMatSoChanging(value);
					this.SendPropertyChanging();
					this._ChiMatSo = value;
					this.SendPropertyChanged("ChiMatSo");
					this.OnChiMatSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiKhoaGoc", DbType="NVarChar(50)")]
		public string ChiKhoaGoc
		{
			get
			{
				return this._ChiKhoaGoc;
			}
			set
			{
				if ((this._ChiKhoaGoc != value))
				{
					this.OnChiKhoaGocChanging(value);
					this.SendPropertyChanging();
					this._ChiKhoaGoc = value;
					this.SendPropertyChanged("ChiKhoaGoc");
					this.OnChiKhoaGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDo", DbType="NVarChar(MAX)")]
		public string LyDo
		{
			get
			{
				return this._LyDo;
			}
			set
			{
				if ((this._LyDo != value))
				{
					this.OnLyDoChanging(value);
					this.SendPropertyChanging();
					this._LyDo = value;
					this.SendPropertyChanged("LyDo");
					this.OnLyDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiMoNuoc", DbType="Int")]
		public System.Nullable<int> PhiMoNuoc
		{
			get
			{
				return this._PhiMoNuoc;
			}
			set
			{
				if ((this._PhiMoNuoc != value))
				{
					this.OnPhiMoNuocChanging(value);
					this.SendPropertyChanging();
					this._PhiMoNuoc = value;
					this.SendPropertyChanged("PhiMoNuoc");
					this.OnPhiMoNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongNuoc2", DbType="Bit NOT NULL")]
		public bool DongNuoc2
		{
			get
			{
				return this._DongNuoc2;
			}
			set
			{
				if ((this._DongNuoc2 != value))
				{
					this.OnDongNuoc2Changing(value);
					this.SendPropertyChanging();
					this._DongNuoc2 = value;
					this.SendPropertyChanged("DongNuoc2");
					this.OnDongNuoc2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDN1", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDN1
		{
			get
			{
				return this._NgayDN1;
			}
			set
			{
				if ((this._NgayDN1 != value))
				{
					this.OnNgayDN1Changing(value);
					this.SendPropertyChanging();
					this._NgayDN1 = value;
					this.SendPropertyChanged("NgayDN1");
					this.OnNgayDN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoDN1", DbType="Int")]
		public System.Nullable<int> ChiSoDN1
		{
			get
			{
				return this._ChiSoDN1;
			}
			set
			{
				if ((this._ChiSoDN1 != value))
				{
					this.OnChiSoDN1Changing(value);
					this.SendPropertyChanging();
					this._ChiSoDN1 = value;
					this.SendPropertyChanged("ChiSoDN1");
					this.OnChiSoDN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongPhi", DbType="Bit NOT NULL")]
		public bool DongPhi
		{
			get
			{
				return this._DongPhi;
			}
			set
			{
				if ((this._DongPhi != value))
				{
					this.OnDongPhiChanging(value);
					this.SendPropertyChanging();
					this._DongPhi = value;
					this.SendPropertyChanged("DongPhi");
					this.OnDongPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenKhoan", DbType="Bit NOT NULL")]
		public bool ChuyenKhoan
		{
			get
			{
				return this._ChuyenKhoan;
			}
			set
			{
				if ((this._ChuyenKhoan != value))
				{
					this.OnChuyenKhoanChanging(value);
					this.SendPropertyChanging();
					this._ChuyenKhoan = value;
					this.SendPropertyChanged("ChuyenKhoan");
					this.OnChuyenKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDongPhi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDongPhi
		{
			get
			{
				return this._NgayDongPhi;
			}
			set
			{
				if ((this._NgayDongPhi != value))
				{
					this.OnNgayDongPhiChanging(value);
					this.SendPropertyChanging();
					this._NgayDongPhi = value;
					this.SendPropertyChanged("NgayDongPhi");
					this.OnNgayDongPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuDN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieuDN
		{
			get
			{
				return this._SoPhieuDN;
			}
			set
			{
				if ((this._SoPhieuDN != value))
				{
					this.OnSoPhieuDNChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuDN = value;
					this.SendPropertyChanged("SoPhieuDN");
					this.OnSoPhieuDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySoPhieuDN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySoPhieuDN
		{
			get
			{
				return this._NgaySoPhieuDN;
			}
			set
			{
				if ((this._NgaySoPhieuDN != value))
				{
					this.OnNgaySoPhieuDNChanging(value);
					this.SendPropertyChanging();
					this._NgaySoPhieuDN = value;
					this.SendPropertyChanged("NgaySoPhieuDN");
					this.OnNgaySoPhieuDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenDN", DbType="Bit NOT NULL")]
		public bool ChuyenDN
		{
			get
			{
				return this._ChuyenDN;
			}
			set
			{
				if ((this._ChuyenDN != value))
				{
					this.OnChuyenDNChanging(value);
					this.SendPropertyChanging();
					this._ChuyenDN = value;
					this.SendPropertyChanged("ChuyenDN");
					this.OnChuyenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenDN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenDN
		{
			get
			{
				return this._NgayChuyenDN;
			}
			set
			{
				if ((this._NgayChuyenDN != value))
				{
					this.OnNgayChuyenDNChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenDN = value;
					this.SendPropertyChanged("NgayChuyenDN");
					this.OnNgayChuyenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuDN1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieuDN1
		{
			get
			{
				return this._SoPhieuDN1;
			}
			set
			{
				if ((this._SoPhieuDN1 != value))
				{
					this.OnSoPhieuDN1Changing(value);
					this.SendPropertyChanging();
					this._SoPhieuDN1 = value;
					this.SendPropertyChanged("SoPhieuDN1");
					this.OnSoPhieuDN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySoPhieuDN1", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySoPhieuDN1
		{
			get
			{
				return this._NgaySoPhieuDN1;
			}
			set
			{
				if ((this._NgaySoPhieuDN1 != value))
				{
					this.OnNgaySoPhieuDN1Changing(value);
					this.SendPropertyChanging();
					this._NgaySoPhieuDN1 = value;
					this.SendPropertyChanged("NgaySoPhieuDN1");
					this.OnNgaySoPhieuDN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenDN1", DbType="Bit NOT NULL")]
		public bool ChuyenDN1
		{
			get
			{
				return this._ChuyenDN1;
			}
			set
			{
				if ((this._ChuyenDN1 != value))
				{
					this.OnChuyenDN1Changing(value);
					this.SendPropertyChanging();
					this._ChuyenDN1 = value;
					this.SendPropertyChanged("ChuyenDN1");
					this.OnChuyenDN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenDN1", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenDN1
		{
			get
			{
				return this._NgayChuyenDN1;
			}
			set
			{
				if ((this._NgayChuyenDN1 != value))
				{
					this.OnNgayChuyenDN1Changing(value);
					this.SendPropertyChanging();
					this._NgayChuyenDN1 = value;
					this.SendPropertyChanged("NgayChuyenDN1");
					this.OnNgayChuyenDN1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TroNgaiMN", DbType="Bit NOT NULL")]
		public bool TroNgaiMN
		{
			get
			{
				return this._TroNgaiMN;
			}
			set
			{
				if ((this._TroNgaiMN != value))
				{
					this.OnTroNgaiMNChanging(value);
					this.SendPropertyChanging();
					this._TroNgaiMN = value;
					this.SendPropertyChanged("TroNgaiMN");
					this.OnTroNgaiMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoNuoc", DbType="Bit NOT NULL")]
		public bool MoNuoc
		{
			get
			{
				return this._MoNuoc;
			}
			set
			{
				if ((this._MoNuoc != value))
				{
					this.OnMoNuocChanging(value);
					this.SendPropertyChanging();
					this._MoNuoc = value;
					this.SendPropertyChanged("MoNuoc");
					this.OnMoNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMN
		{
			get
			{
				return this._NgayMN;
			}
			set
			{
				if ((this._NgayMN != value))
				{
					this.OnNgayMNChanging(value);
					this.SendPropertyChanging();
					this._NgayMN = value;
					this.SendPropertyChanged("NgayMN");
					this.OnNgayMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSoMN", DbType="Int")]
		public System.Nullable<int> ChiSoMN
		{
			get
			{
				return this._ChiSoMN;
			}
			set
			{
				if ((this._ChiSoMN != value))
				{
					this.OnChiSoMNChanging(value);
					this.SendPropertyChanging();
					this._ChiSoMN = value;
					this.SendPropertyChanged("ChiSoMN");
					this.OnChiSoMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieuMN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieuMN
		{
			get
			{
				return this._SoPhieuMN;
			}
			set
			{
				if ((this._SoPhieuMN != value))
				{
					this.OnSoPhieuMNChanging(value);
					this.SendPropertyChanging();
					this._SoPhieuMN = value;
					this.SendPropertyChanged("SoPhieuMN");
					this.OnSoPhieuMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySoPhieuMN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySoPhieuMN
		{
			get
			{
				return this._NgaySoPhieuMN;
			}
			set
			{
				if ((this._NgaySoPhieuMN != value))
				{
					this.OnNgaySoPhieuMNChanging(value);
					this.SendPropertyChanging();
					this._NgaySoPhieuMN = value;
					this.SendPropertyChanged("NgaySoPhieuMN");
					this.OnNgaySoPhieuMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenMN", DbType="Bit NOT NULL")]
		public bool ChuyenMN
		{
			get
			{
				return this._ChuyenMN;
			}
			set
			{
				if ((this._ChuyenMN != value))
				{
					this.OnChuyenMNChanging(value);
					this.SendPropertyChanging();
					this._ChuyenMN = value;
					this.SendPropertyChanged("ChuyenMN");
					this.OnChuyenMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenMN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyenMN
		{
			get
			{
				return this._NgayChuyenMN;
			}
			set
			{
				if ((this._NgayChuyenMN != value))
				{
					this.OnNgayChuyenMNChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenMN = value;
					this.SendPropertyChanged("NgayChuyenMN");
					this.OnNgayChuyenMNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChuTroNgai", DbType="NVarChar(MAX)")]
		public string GhiChuTroNgai
		{
			get
			{
				return this._GhiChuTroNgai;
			}
			set
			{
				if ((this._GhiChuTroNgai != value))
				{
					this.OnGhiChuTroNgaiChanging(value);
					this.SendPropertyChanging();
					this._GhiChuTroNgai = value;
					this.SendPropertyChanged("GhiChuTroNgai");
					this.OnGhiChuTroNgaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaDN
		{
			get
			{
				return this._MaDN;
			}
			set
			{
				if ((this._MaDN != value))
				{
					this.OnMaDNChanging(value);
					this.SendPropertyChanging();
					this._MaDN = value;
					this.SendPropertyChanged("MaDN");
					this.OnMaDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaKy", DbType="Bit NOT NULL")]
		public bool DaKy
		{
			get
			{
				return this._DaKy;
			}
			set
			{
				if ((this._DaKy != value))
				{
					this.OnDaKyChanging(value);
					this.SendPropertyChanging();
					this._DaKy = value;
					this.SendPropertyChanged("DaKy");
					this.OnDaKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKy
		{
			get
			{
				return this._NgayKy;
			}
			set
			{
				if ((this._NgayKy != value))
				{
					this.OnNgayKyChanging(value);
					this.SendPropertyChanging();
					this._NgayKy = value;
					this.SendPropertyChanged("NgayKy");
					this.OnNgayKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
